spring.application.name=sistema_locadora

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/locadora_filmes
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.forward-headers-strategy=framework

app.upload.dir=${UPLOAD_DIR:./uploads/covers}
